// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements the ResolveScheduleConflicts flow to detect and resolve scheduling conflicts.
 *
 * - resolveScheduleConflicts - A function that handles the conflict resolution process.
 * - ResolveScheduleConflictsInput - The input type for the resolveScheduleConflicts function.
 * - ResolveScheduleConflictsOutput - The return type for the resolveScheduleConflicts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ResolveScheduleConflictsInputSchema = z.object({
  schedules: z.string().describe('A list of schedules to check for conflicts, in JSON format.'),
  parameters: z.string().optional().describe('Additional parameters to consider for conflict resolution, in JSON format.'),
});
export type ResolveScheduleConflictsInput = z.infer<typeof ResolveScheduleConflictsInputSchema>;

const ResolveScheduleConflictsOutputSchema = z.object({
  hasConflicts: z.boolean().describe('Whether or not any conflicts were detected.'),
  resolvedSchedules: z.string().describe('The schedules with conflicts resolved, in JSON format.'),
  conflictDetails: z.string().optional().describe('Details about the detected conflicts, in JSON format.'),
});
export type ResolveScheduleConflictsOutput = z.infer<typeof ResolveScheduleConflictsOutputSchema>;

export async function resolveScheduleConflicts(input: ResolveScheduleConflictsInput): Promise<ResolveScheduleConflictsOutput> {
  return resolveScheduleConflictsFlow(input);
}

const resolveScheduleConflictsPrompt = ai.definePrompt({
  name: 'resolveScheduleConflictsPrompt',
  input: {schema: ResolveScheduleConflictsInputSchema},
  output: {schema: ResolveScheduleConflictsOutputSchema},
  prompt: `You are an AI assistant specialized in resolving scheduling conflicts.

You will receive a list of schedules and additional parameters to consider.
Your goal is to identify any conflicts and resolve them based on the provided parameters.

Schedules: {{{schedules}}}
Parameters: {{{parameters}}}

Respond with the resolved schedules, details of any conflicts found, and a boolean indicating whether conflicts were present.

Ensure the resolvedSchedules is a valid JSON.
`,
});

const resolveScheduleConflictsFlow = ai.defineFlow(
  {
    name: 'resolveScheduleConflictsFlow',
    inputSchema: ResolveScheduleConflictsInputSchema,
    outputSchema: ResolveScheduleConflictsOutputSchema,
  },
  async input => {
    try {
      JSON.parse(input.schedules);
      if (input.parameters) {
        JSON.parse(input.parameters);
      }
    } catch (e: any) {
      throw new Error('Invalid JSON format in schedules or parameters: ' + e.message);
    }

    const {output} = await resolveScheduleConflictsPrompt(input);
    return output!;
  }
);
